baseURL = 'http://agileNola.org/'
languageCode = 'en-us'
title = 'Agile Nola'
theme = 'ananke'


DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Agile Nola"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Agile Nola"
  favicon = ""
  site_logo = ""
  description = "Building the New Orleans Tech Community"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

# TODO: Add Social Media links here
# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/{:your_handle_here}"